-- Setup colorscheme
-- vim.cmd("colorscheme github_dark")
-- vim.cmd("colorscheme github_dark_dimmed")
-- vim.cmd("colorscheme github_dark_tritanopia")
-- vim.cmd("colorscheme github_dark_default")
-- vim.cmd("colorscheme github_dark_colorblind")
-- vim.cmd("colorscheme github_dark_high_contrast")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme nightfox")
-- vim.cmd("colorscheme nordfox")
-- vim.cmd("colorscheme terafox")
-- vim.cmd("colorscheme carbonfox")
vim.cmd("colorscheme duskfox")
-- vim.cmd('colorscheme onedark')
-- vim.cmd("colorscheme tokyonight-moon")
-- vim.cmd("colorscheme tokyonight-night")
-- vim.cmd("colorscheme tokyonight-storm")
-- vim.cmd('colorscheme onedark')
-- vim.cmd('colorscheme catppuccin')
-- vim.cmd('colorscheme catppuccin-macchiato')
-- vim.cmd('colorscheme catppuccin-mocha')
-- vim.cmd('colorscheme hardhacker')
-- vim.cmd('colorscheme hardhacker-darker')

-- Set floating window background color to transparent after loading colorscheme
vim.api.nvim_set_hl(0, 'NormalFloat', {bg='None'})

