[buildPlans.iosevka-slab-ss08-0828]
family = "Iosevka SLAB SS08 0828"
spacing = "normal"
serifs = "slab"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-slab-ss08-0828.variants]
  inherits = "ss08"

    [buildPlans.iosevka-slab-ss08-0828.variants.design]
    capital-g = "toothed-serifed-hooked"
    capital-i = "serifed"
    capital-m = "hanging"
    capital-n = "standard"
    capital-p = "closed"
    capital-q = "curly-tailed"
    capital-r = "curly"
    capital-w = "straight"
    a = "double-storey-serifed"
    e = "flat-crossbar"
    f = "serifed"
    g = "double-storey"
    k = "straight-serifed"
    l = "serifed"
    m = "normal"
    n = "straight"
    r = "corner-hooked-serifed"
    s = "bilateral-serifed"
    t = "standard"
    w = "straight"
    x = "curly-serifed"
    y = "straight-turn"
    cyrl-capital-u = "straight-turn"
    zero = "slashed"
    one = "base-long-top-serif"
    two = "curly-neck"
    three = "flat-top"
    four = "closed"
    seven = "straight-serifed"
    asterisk = "turn-hex-low"
    caret = "medium"
    number-sign = "upright"
    ampersand = "upper-open"
    at = "fourfold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    lig-ltgteq = "slanted"
    question = "smooth"
    punctuation-dot = "square"
    lig-neq = "slightly-slanted"

  [buildPlans.iosevka-slab-ss08-0828.ligations]
  inherits = "php"