# An example config to define custom values on each machine.
#
# Copy the content into `custom.toml` in this `custom` directory and all these
# configs will be imported in `../alacritty.toml`.
#
# The `custom.toml` is ignored in git repo so that we can have different configs
# on each machine.
[general]
import = ["../themes/catppuccin-mocha.toml"]

# Disable vi mode by overriding the default keybindings.
#
# On Linux platform, alacritty keyboard freezes after exit vi mode:
#
# https://github.com/alacritty/alacritty/issues/8907
#
# And a workaround for this issue is settings the `XMODIFIERS` env to an empty string,
# but it also disables fcitx.
#
# And in most conditions we use zellij instead of raw alacritty buffering where vi mode
# not works.
#
# Disable the vi mode keybinding for sake.
[[keyboard.bindings]]
mods = "Control | Shift"
key = "Space"
action = "None"

[font]
size = 16.0

[font.normal]
family = "Iosevka1204 Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Iosevka1204 Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka1204 Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Iosevka1204 Nerd Font Mono"
style = "Bold Italic"

