[buildPlans.iosevka1204]
family = "Iosevka1204"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka1204.variants.design]
capital-a = "straight-top-serifed"
capital-b = "standard-unilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed-both-sides"
capital-k = "straight-bottom-right-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-r = "straight-open-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-serifless"
b = "toothless-corner-serifed"
c = "unilateral-inward-serifed"
d = "toothed-top-serifed"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-corner"
h = "tailed-motion-serifed"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-connected-bottom-right-serifed"
l = "serifed-flat-tailed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "eared-motion-serifed"
q = "diagonal-tailed-motion-serifed"
r = "top-serifed"
s = "unilateral-inward-serifed"
t = "flat-hook"
u = "tailed-motion-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-motion-serifed"
y = "straight-motion-serifed"
z = "curly-top-serifed"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-descending"
turn-v = "straight"
lower-alpha = "crossing"
lower-delta = "flat-top"
capital-gamma = "top-right-serifed"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight-turn"
lower-xi = "flat-top"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ef = "serifless"
zero = "tall-slashed"
one = "base"
two = "curly-neck"
three = "flat-top"
four = "closed"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
diacritic-dot = "square"
punctuation-dot = "square"
tilde = "low"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
number-sign = "upright"
ampersand = "et-toothed"
at = "fourfold"
dollar = "interrupted"
percent = "rings-continuous-slash"
bar = "force-upright"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
cent = "through"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.iosevka1204.ligations]
  inherits = "dlig"

[buildPlans.iosevka1204.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka1204.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
