[buildPlans.Iosevka1204]
family = "Iosevka1204"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.Iosevka1204.variants.design]
one = "base"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "closed-serifed"
five = "oblique-arched-serifless"
six = "closed-contour"
seven = "straight-serifed"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "slashed"
capital-a = "straight-top-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "top-left-serifed"
capital-j = "flat-hook-serifed-both-sides"
capital-k = "straight-top-left-and-bottom-right-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-r = "straight-top-left-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-bilateral-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-serifed"
b = "toothed-motion-serifed"
c = "unilateral-serifed"
d = "toothed-serifed"
e = "flat-crossbar"
f = "serifed-crossbar-at-x-height"
g = "double-storey"
h = "straight-motion-serifed"
i = "zshaped"
j = "flat-hook-serifed"
k = "curly-top-left-and-bottom-right-serifed"
l = "zshaped"
m = "serifed"
n = "straight-motion-serifed"
p = "eared-serifed"
q = "straight-serifed"
r = "corner-hooked-serifed"
s = "bilateral-serifed"
t = "flat-hook-short-neck"
u = "toothed-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-unilateral-motion-serifed"
y = "straight-turn-motion-serifed"
z = "curly-top-serifed"
lower-alpha = "crossing"
capital-gamma = "top-right-serifed"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "flat-top"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ef = "serifless"
diacritic-dot = "square"
punctuation-dot = "square"
tilde = "low"
asterisk = "turn-hex-low"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
ampersand = "et-toothed"
at = "fourfold"
dollar = "interrupted"
cent = "through"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.Iosevka1204.ligations]
  inherits = "php"

[buildPlans.Iosevka1204.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosevka1204.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
