" Instrall plugin
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Common settings
set nu
set hls
set cursorline
set noshowmode
set laststatus=2
set showtabline=2
set incsearch
set ruler

" Enable backspace in Windows Terminal + MSYS2
set backspace=indent,eol,start

" Enable Airline tab bar
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'default'

" Set Airline theme
let g:airline_theme='qwq'

